# Copyright (c) 2003-2010 Amnesiac Software Project.
# See the 'COPYRIGHT' file for more information.
if (word(2 $loadinfo()) != [pf]) {
	load -pf $word(1 $loadinfo());
	return;
};

subpackage country;

alias addcountry {
	@:i = numitems(countryIndex);
	@setitem(countryIndex $i $toupper($0));
	@setitem(countryName $i $1-);
};

alias country {
	@:i= matchitem(countryIndex $toupper($0));
	if ( i > -1) {
		@function_return=getitem(countryName $i);
	} {
		@function_return ='Unknown';
	};
};

alias tld {
	xecho $acban $* is $country($*);
};

@addcountry(COM Internic Commercial);
@addcountry(EDU Educational Institution);
@addcountry(GOV Government);
@addcountry(INT International);
@addcountry(MIL Military);
@addcountry(NET Internic Network);
@addcountry(ORG Internic Non-Profit Organization);
@addcountry(ARPA Reverse DNS);
@addcountry(aero Air-transport industry);
@addcountry(biz Business);
@addcountry(cat Catlan);
@addcountry(coop Cooperative association);
@addcountry(info inph0);
@addcountry(jobs Human resource management);
@addcountry(mobi Mobile products);
@addcountry(museum working da MuSeUm);
@addcountry(name Induvidual (phEar));
@addcountry(pro Credentialed professional (phEar));
@addcountry(tel Owns you);
@addcountry(travel Take a wild guess);
@addcountry(ac Ascension Island);
@addcountry(ad Andorra);
@addcountry(ae United Arab Emirates);
@addcountry(af Afghanistan);
@addcountry(ag Antigua and Barbuda);
@addcountry(ai Anguilla);
@addcountry(al Albania);
@addcountry(am Armenia);
@addcountry(an Netherlands Antilles);
@addcountry(ao Angola);
@addcountry(aq Antarctica);
@addcountry(ar Argentina);
@addcountry(as American Samoa);
@addcountry(at Austria);
@addcountry(au Australia);
@addcountry(aw Aruba);
@addcountry(ax Aland Islands);
@addcountry(az Azerbaijan);
@addcountry(ba Bosnia and Herzegovina);
@addcountry(bb Barbados);
@addcountry(bd Bangladesh);
@addcountry(be Belgium);
@addcountry(bf Burkina Faso);
@addcountry(bg Bulgaria);
@addcountry(bh Bahrain);
@addcountry(bi Burundi);
@addcountry(bj Benin);
@addcountry(bm Bermuda);
@addcountry(bn Brunei Darussalam);
@addcountry(bo Bolivia);
@addcountry(br Brazil);
@addcountry(bs Bahamas);
@addcountry(bt Bhutan);
@addcountry(bv Bouvet Island);
@addcountry(bw Botswana);
@addcountry(by Belarus);
@addcountry(bz Belize);
@addcountry(ca Canada);
@addcountry(cc Cocos (Keeling) Islands);
@addcountry(cd Congo, The Democratic Republic of the);
@addcountry(cf Central African Republic);
@addcountry(cg Congo, Republic of);
@addcountry(ch Switzerland);
@addcountry(ci Cote d'Ivoire);
@addcountry(ck Cook Islands);
@addcountry(cl Chile);
@addcountry(cm Cameroon);
@addcountry(cn China);
@addcountry(co Colombia);
@addcountry(cr Costa Rica);
@addcountry(cu Cuba);
@addcountry(cv Cape Verde);
@addcountry(cx Christmas Island);
@addcountry(cy Cyprus);
@addcountry(cz Czech Republic);
@addcountry(de Germany);
@addcountry(dj Djibouti);
@addcountry(dk Denmark);
@addcountry(dm Dominica);
@addcountry(do Dominican Republic);
@addcountry(dz Algeria);
@addcountry(ec Ecuador);
@addcountry(ee Estonia);
@addcountry(eg Egypt);
@addcountry(eh Western Sahara);
@addcountry(er Eritrea);
@addcountry(es Spain);
@addcountry(et Ethiopia);
@addcountry(eu European Union);
@addcountry(fi Finland);
@addcountry(fj Fiji);
@addcountry(fk Falkland Islands (Malvinas));
@addcountry(fm Micronesia, Federated States of);
@addcountry(fo Faroe Islands);
@addcountry(fr France);
@addcountry(ga Gabon);
@addcountry(gb United Kingdom);
@addcountry(gd Grenada);
@addcountry(ge Georgia);
@addcountry(gf French Guiana);
@addcountry(gg Guernsey);
@addcountry(gh Ghana);
@addcountry(gi Gibraltar);
@addcountry(gl Greenland);
@addcountry(gm Gambia);
@addcountry(gn Guinea);
@addcountry(gp Guadeloupe);
@addcountry(gq Equatorial Guinea);
@addcountry(gr Greece);
@addcountry(gs South Georgia and the South Sandwich Islands);
@addcountry(gt Guatemala);
@addcountry(gu Guam);
@addcountry(gw Guinea-Bissau);
@addcountry(gy Guyana);
@addcountry(hk Hong Kong);
@addcountry(hm Heard and McDonald Islands);
@addcountry(hn Honduras);
@addcountry(hr Croatia/Hrvatska);
@addcountry(ht Haiti);
@addcountry(hu Hungary);
@addcountry(id Indonesia);
@addcountry(ie Ireland);
@addcountry(il Israel);
@addcountry(im Isle of Man);
@addcountry(in India);
@addcountry(io British Indian Ocean Territory);
@addcountry(iq Iraq);
@addcountry(ir Iran, Islamic Republic of);
@addcountry(is Iceland);
@addcountry(it Italy);
@addcountry(je Jersey);
@addcountry(jm Jamaica);
@addcountry(jo Jordan);
@addcountry(jp Japan);
@addcountry(ke Kenya);
@addcountry(kg Kyrgyzstan);
@addcountry(kh Cambodia);
@addcountry(ki Kiribati);
@addcountry(km Comoros);
@addcountry(kn Saint Kitts and Nevis);
@addcountry(kp Korea, Democratic People's Republic);
@addcountry(kr Korea, Republic of);
@addcountry(kw Kuwait);
@addcountry(ky Cayman Islands);
@addcountry(kz Kazakhstan);
@addcountry(la Lao People's Democratic Republic);
@addcountry(lb Lebanon);
@addcountry(lc Saint Lucia);
@addcountry(li Liechtenstein);
@addcountry(lk Sri Lanka);
@addcountry(lr Liberia);
@addcountry(ls Lesotho);
@addcountry(lt Lithuania);
@addcountry(lu Luxembourg);
@addcountry(lv Latvia);
@addcountry(ly Libyan Arab Jamahiriya);
@addcountry(ma Morocco);
@addcountry(mc Monaco);
@addcountry(md Moldova, Republic of);
@addcountry(me Montenegro);
@addcountry(mg Madagascar);
@addcountry(mh Marshall Islands);
@addcountry(mk Macedonia, The Former Yugoslav Republic of);
@addcountry(ml Mali);
@addcountry(mm Myanmar);
@addcountry(mn Mongolia);
@addcountry(mo Macao);
@addcountry(mp Northern Mariana Islands);
@addcountry(mq Martinique);
@addcountry(mr Mauritania);
@addcountry(ms Montserrat);
@addcountry(mt Malta);
@addcountry(mu Mauritius);
@addcountry(mv Maldives);
@addcountry(mw Malawi);
@addcountry(mx Mexico);
@addcountry(my Malaysia);
@addcountry(mz Mozambique);
@addcountry(na Namibia);
@addcountry(nc New Caledonia);
@addcountry(ne Niger);
@addcountry(nf Norfolk Island);
@addcountry(ng Nigeria);
@addcountry(ni Nicaragua);
@addcountry(nl Netherlands);
@addcountry(no Norway);
@addcountry(np Nepal);
@addcountry(nr Nauru);
@addcountry(nu Niue);
@addcountry(nz New Zealand);
@addcountry(om Oman);
@addcountry(pa Panama);
@addcountry(pe Peru);
@addcountry(pf French Polynesia);
@addcountry(pg Papua New Guinea);
@addcountry(ph Philippines);
@addcountry(pk Pakistan);
@addcountry(pl Poland);
@addcountry(pm Saint Pierre and Miquelon);
@addcountry(pn Pitcairn Island);
@addcountry(pr Puerto Rico);
@addcountry(ps Palestinian Territory, Occupied);
@addcountry(pt Portugal);
@addcountry(pw Palau);
@addcountry(py Paraguay);
@addcountry(qa Qatar);
@addcountry(re Reunion Island);
@addcountry(ro Romania);
@addcountry(rs Serbia);
@addcountry(ru Russian Federation);
@addcountry(rw Rwanda);
@addcountry(sa Saudi Arabia);
@addcountry(sb Solomon Islands);
@addcountry(sc Seychelles);
@addcountry(sd Sudan);
@addcountry(se Sweden);
@addcountry(sg Singapore);
@addcountry(sh Saint Helena);
@addcountry(si Slovenia);
@addcountry(sj Svalbard and Jan Mayen Islands);
@addcountry(sk Slovak Republic);
@addcountry(sl Sierra Leone);
@addcountry(sm San Marino);
@addcountry(sn Senegal);
@addcountry(so Somalia);
@addcountry(sr Suriname);
@addcountry(st Sao Tome and Principe);
@addcountry(su Soviet Union);
@addcountry(sv El Salvador);
@addcountry(sy Syrian Arab Republic);
@addcountry(sz Swaziland);
@addcountry(tc Turks and Caicos Islands);
@addcountry(td Chad);
@addcountry(tf French Southern Territories);
@addcountry(tg Togo);
@addcountry(th Thailand);
@addcountry(tj Tajikistan);
@addcountry(tk Tokelau);
@addcountry(tl Timor-Leste);
@addcountry(tm Turkmenistan);
@addcountry(tn Tunisia);
@addcountry(to Tonga);
@addcountry(tp East Timor);
@addcountry(tr Turkey);
@addcountry(tt Trinidad and Tobago);
@addcountry(tv Tuvalu);
@addcountry(tw Taiwan);
@addcountry(tz Tanzania);
@addcountry(ua Ukraine);
@addcountry(ug Uganda);
@addcountry(uk United Kingdom);
@addcountry(um United States Minor Outlying Islands);
@addcountry(us United States);
@addcountry(uy Uruguay);
@addcountry(uz Uzbekistan);
@addcountry(va Holy See);
@addcountry(vc Saint Vincent and the Grenadines);
@addcountry(ve Venezuela);
@addcountry(vg Virgin Islands, British);
@addcountry(vi Virgin Islands, U.S.);
@addcountry(vn Vietnam);
@addcountry(vu Vanuatu);
@addcountry(wf Wallis and Futuna Islands);
@addcountry(ws Samoa);
@addcountry(ye Yemen);
@addcountry(yt Mayotte);
@addcountry(yu Yugoslavia);
@addcountry(za South Africa);
@addcountry(zm Zambia);
@addcountry(zw Zimbabwe);
